config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help",   to:'static_pages#help'
  get "/about",  to:'static_pages#about'
  get "/contact",to:'static_pages#contact'
  get "/signup" ,to:"users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout",to:"sessions#destroy"
  post "/likes/:micropost_id/create", to:"likes#create", as: 'create_like'
  delete "/likes/:micropost_id/delete", to:"likes#destroy", as: 'delete_like'
  resources :users do
    member do
      get :following, :followers
    end
    collection do
      get :search
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts, only:[:create,:destroy,:show] do
    member do
      get :most_liked
      get :newest
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :blocks, only: [:create, :destroy]
  resources :chat_rooms, only: [:index, :show, :create] do
    resources :chat_messages, only: [:create]
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :chat_rooms_users
    has_many :chat_rooms, through: :chat_rooms_users
    has_many :active_blocks,class_name:"Block",
                            foreign_key: "blocker_id",
                            dependent: :destroy
    has_many :passive_blocks,class_name: "Block",
                            foreign_key: "blocked_id",
                            dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_microposts, through: :likes, source: :micropost
    has_many :microposts ,dependent: :destroy 
    has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
    has_many :passive_relationships, class_name:  "Relationship",
                                  foreign_key: "followed_id",
                                  dependent:   :destroy

    has_many :blocking,through: :active_blocks,source: :blocked
    has_many :blockers,through: :passive_blocks,source: :blocker
    has_many :following, through: :active_relationships, source: :followed
    has_many :followers, through: :passive_relationships, source: :follower
    attr_accessor :remember_token ,:activation_token,:reset_token
    before_save { email.downcase! }
    before_create :create_activation_digest
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: true
    has_secure_password
    validates :password,presence:true,length:{minimum:6},allow_nil: true

    #渡された文字列ハッシュ化
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token
        #バリデーションを素通りさせる
        update_attribute(:remember_digest,User.digest(remember_token))
        remember_digest
    end

    # 渡されたトークンがダイジェストと一致したらtrueを返す
    # def authenticated?(attribute, token)
    #     digest = send("#{attribute}_digest")
    #     return false if digest.nil?
    #     BCrypt::Password.new(digest).is_password?(token)
    # end
    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end

    def forget
        update_attribute(:remember_digest,nil)
    end

    def session_token
        remember_digest || remember
    end

    # アカウントを有効にする
    # def activate
    #     update_attribute(:activated,    true)
    #     update_attribute(:activated_at, Time.zone.now)
    # end
    
    def activate
        update_columns(activated: true,activated_at: Time.zone.now)
    end

    # 有効化用のメールを送信する
    def send_activation_email
        UserMailer.account_activation(self).deliver_now
    end

     # パスワード再設定の属性を設定する
    def create_reset_digest
        self.reset_token = User.new_token
        update_attribute(:reset_digest,  User.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
    end

    

    # パスワード再設定のメールを送信する
    def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
    end

    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end

    # def feed
    #     Micropost.where("user_id = ?", id)
    # end

    # ユーザーをフォローする
    def follow(other_user)
        following << other_user unless self == other_user
    end

    # ユーザーをフォロー解除する
    def unfollow(other_user)
        following.delete(other_user)
    end

    # 現在のユーザーが他のユーザーをフォローしていればtrueを返す
    def following?(other_user)
        following.include?(other_user)
    end

    # ユーザーのステータスフィードを返す
    def feed(blockers_user_ids = [])
        following_ids = "SELECT followed_id FROM relationships
                        WHERE  follower_id = :user_id"
        Micropost.where("user_id IN (#{following_ids})
                         OR user_id = :user_id", user_id: id)
                        .where.not(user_id: blockers_user_ids)
                        .includes(:user, image_attachment: :blob)
    end

    #いいね機能
    def like(micropost)
        likes.create(micropost_id: micropost.id)
    end

    def unlike(micropost)
        likes.find_by(micropost_id:micropost.id).destroy
    end

     # ユーザーをブロックする
    def block(other_user)
        blocking << other_user unless blocked?(other_user) || self == other_user
    end

    # ユーザーのブロックを解除する
    def unblock(other_user)
        blocking.delete(other_user)
    end

    # 現在のユーザーが他のユーザーをブロックしていればtrueを返す
    def blocked?(other_user)
        blocking.include?(other_user)
    end
    # 他のユーザーが現在のユーザーをブロックしていればtrueを返す
    def blocked_by?(other_user)
        blockers.include?(other_user)
    end
    

    private
        # 有効化トークンとダイジェストを作成および代入する
        def create_activation_digest
            self.activation_token  = User.new_token
            self.activation_digest = User.digest(activation_token)
        end
        
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update,:index,:destroy,:following, :followers,:search]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user, only: :destroy 
  before_action :check_blocked_user, only: [:show]
  before_action :check_blocked_user_redirect, only: [:following, :followers]
  
  def index
    @title = "All users"
    @users = User.where(activated: true).where.not(id: blockers_user_ids).paginate(page: params[:page])
  end

  def show 
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    redirect_to root_url and return unless @user.activated?
  end

  def new
    @user = User.new 
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new', status: :unprocessable_entity
    end
  end
  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url, status: :see_other
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  def search
    @title = "Search users"
    @users = User.where('name LIKE ?', "%#{params[:query]}%")
               .where(activated: true)
               .where.not(id: blockers_user_ids)
               .paginate(page: params[:page])
    render 'index'
  end

  private

    def user_params
      params.require(:user).permit(:name,:email,:password,
      :password_confirmation)
    end

    

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url, status: :see_other) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url,status: :see_other) unless current_user.admin?
    end
    # ユーザーがブロックされているかどうかを確認
    def check_blocked_user
      if current_user.blocked_by?(User.find(params[:id]))
        flash.now[:danger] = "You have been blocked by this user."
      end
      # if current_user.nil? 
      #   # 例えば、エラーメッセージを表示する、リダイレクトするなどの処理
      #   redirect_to root_url
      # elsif current_user.blocked_by?(User.find(params[:id]))
      #   redirect_to root_url
      # end
    end
    def check_blocked_user_redirect
      if current_user.blocked_by?(User.find(params[:id]))
        flash.now[:danger] = "You have been blocked by this user."
        @user = User.find(params[:id])
        redirect_to user_path(@user)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper

    # 引数で与えられたユーザーのGravatar画像を返す
    def gravatar_for(user,options = {size:80})
      size = options[:size]
      gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
      image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
  end
  

app/views/users/_block_form.html.erb
<% unless current_user == @user %>
  <% if current_user.blocked?(@user) %>
    <%= button_to 'Unblock', block_path(@user), method: :delete, class: 'btn btn-secondary block-button' %>
  <% else %>
    <%= button_to 'Block', blocks_path(blocked_id: @user.id), method: :post, class: 'btn btn-danger block-button' %>
  <% end %>
<% end %>

app/views/users/_chat_room_form.erb
<% unless current_user == @user %>
    <%= form_with(url: chat_rooms_path, method: :post, local: true) do |f| %>
        <%= hidden_field_tag :user_id, @user.id %>
        <%= f.submit "DM", class: "btn btn-primary block-button" %>
    <% end %>
<% end %>

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build) do |f| %>
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "Follow", class: "btn btn-primary" %>
  <% end %>
  

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
  
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>
  

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed: @user),
              html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, data: { "turbo-method": :delete,
                                          turbo_confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="https://gravatar.com/emails" target="_blank" rel="noopener">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, @title) %>
<h1><%= @title %></h1>

<div class="search-container">
  <h4>User Search</h4>
  <%= form_with url: search_users_path, method: :get, class: 'search-form' do |form| %>
    <div class="input-group">
      <%= form.text_field :query, value: params[:query], placeholder: 'Search by name', class: 'form-control' %>
      <button type="submit" class="btn btn-outline-secondary">
        <i class="bi bi-search"></i>
      </button>
    </div>
  <% end %>
  </div>
</div>
<div class="container">
  <%= will_paginate %>
    <ul class="users">
      <%= render @users %>
    </ul>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title,'Sign up')%>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>      
      </h1>
      <!--# <%= render 'block_form' if logged_in? %>
      # <%= render 'chat_room_form' if logged_in? %> -->
      
      <% if logged_in? %>
        <div class="forms-container">
          <%= render 'block_form' %>
          <%= render 'chat_room_form' %>
        </div>
      <% end %>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
  <% if current_user.blocked_by?(@user) %>
  <p>You are blocked by this user and cannot interact with their content.</p>
  <% else %>
  <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
    <% end %>
  </div>
</div>


app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><strong>Microposts:</strong> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>