config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help",   to:'static_pages#help'
  get "/about",  to:'static_pages#about'
  get "/contact",to:'static_pages#contact'
  get "/signup" ,to:"users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout",to:"sessions#destroy"
  post "/likes/:micropost_id/create", to:"likes#create", as: 'create_like'
  delete "/likes/:micropost_id/delete", to:"likes#destroy", as: 'delete_like'
  resources :users do
    member do
      get :following, :followers
    end
    collection do
      get :search
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts, only:[:create,:destroy,:show] do
    member do
      get :most_liked
      get :newest
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :blocks, only: [:create, :destroy]
  resources :chat_rooms, only: [:index, :show, :create] do
    resources :chat_messages, only: [:create]
  end
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :parent_post,class_name: "Micropost",optional: true
  has_many :replies,class_name: "Micropost",foreign_key: "parent_post_id"
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  belongs_to :user
  has_one_attached :image do |attachable|
    attachable.variant :display, resize_to_limit: [500, 500]
  end
  #has_one_attached :image 
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true 
  validates :content,presence:true,length:{maximum: 140}
  validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                      message: "must be a valid image format" },
                      size:         { less_than: 5.megabytes,
                                      message:   "should be less than 5MB" }
   # スコープを追加
   scope :most_liked, ->(parent_post_id) {
  left_joins(:likes)
    .where(parent_post_id: parent_post_id)
    .group(:id)
    .unscope(:order) 
    .order('COUNT(likes.id) DESC')
    .select('microposts.*, COUNT(likes.id) as like_count')
}
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy,:show]
    before_action :correct_user,   only: :destroy

    def create
        @micropost = current_user.microposts.build(micropost_params)
        @micropost.image.attach(params[:micropost][:image])
        if @micropost.save
            flash[:success] = "Micropost created!"
            if @micropost.parent_post_id
                redirect_to micropost_path(@micropost.parent_post_id)
            else
                redirect_to root_url
            end
        else
            @feed_items = current_user.feed.paginate(page: params[:page])
            render 'static_pages/home', status: :unprocessable_entity
        end
    end

    def destroy
        @micropost.destroy
        flash[:success] = "Micropost deleted"
        if request.referrer.nil?
            redirect_to root_url, status: :see_other
        else
            redirect_to request.referrer, status: :see_other
        end
    end

    def show
        @micropost = Micropost.find_by(id: params[:id])
        if @micropost
            @reply = current_user.microposts.build(parent_post_id: @micropost.id)
            @feed_items = Micropost.where("parent_post_id = ?", @micropost.id).paginate(page: params[:page])
        else
            flash[:danger] = "Micropost not found"
            redirect_to root_url
        end
    end

    def most_liked
        @micropost = Micropost.find_by(id: params[:id]) 
        if @micropost
            @reply = current_user.microposts.build(parent_post_id: @micropost.id)
            @feed_items = Micropost
                .most_liked(@micropost.id)
                .paginate(page: params[:page])
            render "show"
        else
            flash[:danger] = "Micropost not found"
            redirect_to root_url
        end
    end
    
    def newest
        @micropost = Micropost.find_by(id: params[:id])
        if @micropost
            @reply = current_user.microposts.build(parent_post_id: @micropost.id)
            @feed_items = Micropost.where("parent_post_id = ?", @micropost.id).paginate(page: params[:page])
            render "show"
        else
            flash[:danger] = "Micropost not found"
            redirect_to root_url
        end
    end

    private

    def micropost_params
        params.require(:micropost).permit(:content,:image,:parent_post_id)
    end

    def correct_user
        @micropost = current_user.microposts.find_by(id: params[:id])
        redirect_to root_url, status: :see_other if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>" class="micropost-hover" onclick="if(event.target.tagName !== 'A' && !event.target.closest('a')) location.href='<%= micropost_path(micropost) %>'" >
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
    <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
    <span class="content">
        <%= micropost.content %>
        <% if micropost.image.attached? %>
            <%= image_tag micropost.image.variant(:display) %>
        <% end %>
    </span>
    <span class="actions">
        <i class="bi bi-chat-dots"></i>
        <%= pluralize(Micropost.where(parent_post_id: micropost.id).count, "reply") %>
        <% if current_user && micropost %>
            <% if Like.find_by(user_id: current_user.id, micropost_id: micropost.id) %>
                <%= link_to delete_like_url(micropost.id), data: { "turbo-method": :delete }, class: "unlike-link", title: "いいねを消す" do %>
                    <i class="bi bi-heart-fill text-danger"></i>
                <% end %>
            <% else %>
                <%= link_to create_like_url(micropost.id), data: { "turbo-method": :post }, class: "like-link", title: "いいね！" do %>
                    <i class="bi bi-heart text-secondary"></i>
                <% end %>
            <% end %>
            <%= pluralize(Like.where(micropost_id: micropost.id).count, "like") %>
        <% else %>
            <p>ユーザーまたはマイクロポストが見つかりません</p>
        <% end %>
    </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, data: { "turbo-method": :delete,
                                               turbo_confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/microposts/show.html.erb
<h1>Micropost</h1>
<div class="col-md-12">     
  <ol class="microposts">
    <%= render @micropost %>
  </ol>
   <%= render 'shared/micropost_reply_form', micropost: @reply %>
   <%if @feed_items.any?%>
   <h3>Reply</h3>
   <div class="sort-options">
    <a href="#" id="sort-toggle" class="dropdown-toggle">
        返信を並び替え <b class="caret"></b>
    </a>
    <div id="sort-menu" class="sort-menu collapse">
        
        <ul>
        <li><a href="<%= newest_micropost_path(@micropost) %>" id="sort-newest">新着順</a></li>
        <li><a href="<%= most_liked_micropost_path(@micropost) %>" id="sort-liked">いいねが多い順</a></li>
        </ul>
    </div>
    </div>
    <% end %>

   <%= render 'shared/feed' %>
</div>